# Help Commands
.PHONY: default
default: help

# Main Commands
.PHONY: run
run:
	javac *.java
	java Main

.PHONY: clean
clean:
	rm -rf *.class

.PHONY: help
help:
	@echo 'Usage: make [command]'
	@echo 'run: - '
